### ISSUE TITLE
HTML: Duplicate IDs for imageUpload.

### ISSUE THREAD

**Issue by Raja-Muhammad-Bilal-Arshad** [theajmalrazaq/CertEdit#14]
HTML code contains duplicate IDs for the 'imageUpload' input element. In HTML, IDs must be unique within a document. Having multiple elements with the same ID can lead to unexpected behavior when trying to access those elements via JavaScript or CSS.

Do let me know when you are good to go..

**Comment by theajmalrazaq** [comment]
@Raja-Muhammad-Bilal-Arshad Good to go!

**Comment by Raja-Muhammad-Bilal-Arshad** [comment]
Jazakallah Kayr Bhai, I will do it right away and start working on it.
