### ISSUE TITLE
CSS: Incorrect path for the font file and potential issues with the logo path and card background.

### ISSUE THREAD

**Issue by Raja-Muhammad-Bilal-Arshad** [theajmalrazaq/CertEdit#15]
[1]. Incorrect Path for the Favicon:
[2]. Potential Issues with Logo Path:
[3]. Does not properly define a background for the card elements:

Do let me know...

**Comment by theajmalrazaq** [comment]
@Raja-Muhammad-Bilal-Arshad change path and test them locally after that create PR

**Comment by Raja-Muhammad-Bilal-Arshad** [comment]
O.k bhai I am on it.
