### ISSUE TITLE
Enhance Styling of Website

### ISSUE THREAD

**Issue by KrishnaSaxena108** [theajmalrazaq/CertEdit#2]
Hi @theajmalrazaq , I want to enhance the overall look of website with Cascading Style Sheets (CSS) and make it responsive.
Kindly assign this issue to me under HacktoberFest 2024.
Thankyou

**Comment by theajmalrazaq** [comment]
@KrishnaSaxena108 You are good to go!!

**Comment by KrishnaSaxena108** [comment]
Sure!! Thankyou For This Opportunity
