### ISSUE TITLE
Bug in UI

### ISSUE THREAD

**Issue by sp9324** [theajmalrazaq/CertEdit#5]
![image](https://github.com/user-attachments/assets/4451c7bb-87b8-4653-9975-917d4b1a65f1)
![image](https://github.com/user-attachments/assets/4ccefe63-9783-4d1a-a2a7-5d4165eb18b7)
Mouse should change to pointer when it hovers on "select name list", "select certificate image" and "select custom font" buttons.
Kindly assign this issue to me, @theajmalrazaq

**Comment by theajmalrazaq** [comment]
@sp9324 You are good to go!

**Comment by theajmalrazaq** [comment]
@sp9324 You are good to go!
